version: '3'

services:
  ecommerce-admin:
    image: bitnami/mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ecommerce